#!/usr/bin/env php
<?php

/*
 * This file is part of Shudd3r/Package-Files package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$rootDir = getcwd();
if (!file_exists($rootDir . '/vendor/autoload.php')) {
    fwrite(STDERR, 'Cannot find composer vendor/autoload.php file in this directory');
    die(1);
}

require_once $rootDir . '/vendor/autoload.php';

$input = function (string $prompt, string $default = ''): string {
    $defaultInfo = $default ? ' [default: ' . $default . ']' : '';
    echo $prompt . $defaultInfo . ': ';
    $input = fopen('php://stdin', 'r');
    $line  = trim(fgets($input));
    fclose($input);
    if ($line === '!') {
        echo '...cancelled' . PHP_EOL;
        exit;
    }
    return $line ?: $default;
};

$build = new Shudd3r\PackageFiles\PackageBuild($input, __DIR__ . DIRECTORY_SEPARATOR . 'skeleton');
$build->run([isset($argv[1]) ? $argv[1] : getcwd()]);
