#!/usr/bin/env php
<?php

/*
 * This file is part of Shudd3r/Package-Files package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Shudd3r\PackageFiles\Application;
use Shudd3r\PackageFiles\Files;
use Shudd3r\PackageFiles\RuntimeEnv;
use Shudd3r\PackageFiles\Command;


// This script is assumed to be one of composer dependencies of the package
// located in $rootDirectory/vendor/shudd3r/package-files directory
$rootDirectory = dirname(__DIR__, 3);
if (!file_exists($rootDirectory . '/vendor/autoload.php')) {
    fwrite(STDERR, 'Cannot find vendor/autoload.php file in package root directory');
    die(1);
}

if (!file_exists($rootDirectory . '/composer.json')) {
    fwrite(STDERR, 'Cannot find composer.json file in package root directory');
    die(1);
}

require_once $rootDirectory . '/vendor/autoload.php';

$terminal      = new Application\Terminal(STDIN, STDOUT, STDERR);
$skeletonFiles = new Files\Directory(__DIR__ . DIRECTORY_SEPARATOR . 'skeleton');
$packageFiles  = new Files\Directory($rootDirectory);
$environment   = new RuntimeEnv($terminal, $packageFiles, $skeletonFiles);

$app = new Application($environment, [
    'init' => Command\Factory\InitCommandFactory::class
]);

$options = getopt('i', ['package:', 'repo:', 'desc:', 'interactive'], $commandIdx);
$command = $argv[$commandIdx] ?? 'init';

$exitCode = $app->run($command, $options);
exit($exitCode);
