#!/usr/bin/env php
<?php

/*
 * This file is part of Shudd3r/Package-Files package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Shudd3r\PackageFiles\Files\ProjectFiles;
use Shudd3r\PackageFiles\Terminal;
use Shudd3r\PackageFiles\Build;


// This script is assumed to be one of composer dependencies of the package
// located in $rootDir/vendor/shudd3r/package-files directory
$rootDirectory = dirname(dirname(dirname(__DIR__)));
if (!file_exists($rootDirectory . '/vendor/autoload.php')) {
    fwrite(STDERR, 'Cannot find vendor/autoload.php file in package root directory');
    die(1);
}

if (!file_exists($rootDirectory . '/composer.json')) {
    fwrite(STDERR, 'Cannot find composer.json file in package root directory');
    die(1);
}

require_once $rootDirectory . '/vendor/autoload.php';

$terminal = new class() implements Terminal
{
    public function input(): string
    {
        $stdin = fopen('php://stdin', 'r');
        $line  = trim(fgets($stdin));
        fclose($stdin);

        if ($line === '!') {
            $this->display('...cancelled' . PHP_EOL);
            exit;
        }

        return $line;
    }

    public function display(string $message): void
    {
        echo $message;
    }
};

$skeletonFiles = new ProjectFiles(__DIR__ . DIRECTORY_SEPARATOR . 'skeleton');
$packageFiles  = new ProjectFiles($rootDirectory);

$build = new Build($terminal, $skeletonFiles, $packageFiles);
$build->run(getopt('', ['package:', 'repo:', 'desc:']));
