#!/usr/bin/env php
<?php

/*
 * This file is part of Shudd3r/Package-Files package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

use Shudd3r\PackageFiles\Build;
use Shudd3r\PackageFiles\Files;
use Shudd3r\PackageFiles\RuntimeEnv;
use Shudd3r\PackageFiles\CommandMap;
use Shudd3r\PackageFiles\Command;
use Shudd3r\PackageFiles\Terminal;


// This script is assumed to be one of composer dependencies of the package
// located in $rootDirectory/vendor/shudd3r/package-files directory
$rootDirectory = dirname(dirname(dirname(__DIR__)));
if (!file_exists($rootDirectory . '/vendor/autoload.php')) {
    fwrite(STDERR, 'Cannot find vendor/autoload.php file in package root directory');
    die(1);
}

if (!file_exists($rootDirectory . '/composer.json')) {
    fwrite(STDERR, 'Cannot find composer.json file in package root directory');
    die(1);
}

require_once $rootDirectory . '/vendor/autoload.php';

$terminal = new class() implements Terminal {
    public function input(): string
    {
        $stdin = fopen('php://stdin', 'r');
        $line  = trim(fgets($stdin));
        fclose($stdin);

        if ($line === '!') {
            $this->display('...cancelled' . PHP_EOL);
            exit;
        }

        return $line;
    }

    public function display(string $message): void
    {
        echo $message;
    }
};

$skeletonFiles = new Files\ProjectFiles(__DIR__ . DIRECTORY_SEPARATOR . 'skeleton');
$packageFiles  = new Files\ProjectFiles($rootDirectory);
$environment   = new RuntimeEnv($terminal, $packageFiles, $skeletonFiles);

$commands = new CommandMap($environment, [
    'init' => function (RuntimeEnv $env) {
        $composerFile = new Files\File('composer.json', $env->packageFiles());
        return new Command\GenerateComposer($composerFile);
    }
]);

$build = new Build($environment, $commands);

$command = $argv[1] ?? 'init';
$options = getopt('i', ['package:', 'repo:', 'desc:', 'interactive']);

$build->run($command, $options);
